# Generated by Django 4.2 on 2023-05-17 08:28

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanticket',
            name='booking_date',
            field=models.DateTimeField(blank=True, help_text='date and time must be grater than now', null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 17, 8, 28, 48, 472893, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='routepart',
            name='arrival',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 17, 8, 28, 48, 474264, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='routepart',
            name='departure',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 17, 8, 28, 48, 474248, tzinfo=datetime.timezone.utc))]),
        ),
    ]
