# Generated by Django 4.2.1 on 2023-05-26 21:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Confirmed', 'Confirmed')], default='Booked', max_length=10),
        ),
        migrations.AlterField(
            model_name='humanticket',
            name='booking_date',
            field=models.DateTimeField(blank=True, help_text='date and time must be grater than now', null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 26, 21, 34, 5, 640340, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='routepart',
            name='arrival',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 26, 21, 34, 5, 641652, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='routepart',
            name='departure',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 26, 21, 34, 5, 641638, tzinfo=datetime.timezone.utc))]),
        ),
    ]
