# Generated by Django 4.2.1 on 2023-05-26 21:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_remove_ticket_is_booked_ticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanticket',
            name='booking_date',
            field=models.DateTimeField(blank=True, help_text='date and time must be grater than now', null=True, validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 26, 21, 39, 51, 711927, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='routepart',
            name='arrival',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 26, 21, 39, 51, 713068, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='routepart',
            name='departure',
            field=models.DateTimeField(help_text='date and time must be grater than now', validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 5, 26, 21, 39, 51, 713056, tzinfo=datetime.timezone.utc))]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Booked', max_length=10),
        ),
    ]
