name: Проверка
on: [push]
jobs:
  container-job:
    name: Тесты
    runs-on: ubuntu-latest
    steps:
    - name: Установка GDAL
      run: |
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
    - name: Set up PostGIS
      run: |
        sudo apt-get -y update
        sudo apt-get -y install postgis
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10.6"
    - name: Запуск postgis контейнера
      run: |
        docker run -d\
          --name trains -p 5555:5432 \
          -v $HOME/postgresql/RR_final:/var/lib/postgresql/RR_final \
          -e POSTGRES_PASSWORD=0000 \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_DB=trains_db \
          -d postgis/postgis
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r RussianRailways/requirements.txt
        echo "POSTGRES_PORT=5555" >> RussianRailways/.env
        echo "POSTGRES_USER=postgres" >> RussianRailways/.env
        echo "POSTGRES_PASSWORD=0000" >> RussianRailways/.env
        echo "POSTGRES_DB=trains_db" >> RussianRailways/.env
        echo "POSTGRES_HOST=127.0.0.1" >> RussianRailways/.env
    - name: Тесты django views
      run: |
        python3 manage.py test tests.test_views
    - name: Тесты django rest api
      run: |
        python3 manage.py test tests.test_rest
    - name: Тесты django names
      run: |
        python3 manage.py test tests.test_names
    - name: Тесты django wrong
      run: |
        python3 manage.py test tests.test_wrong
